main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Login.as_view(), name='login'),
  path('home/', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('accounts/signup/', views.signup, name='signup'),
  path('workouts/', views.workout_index, name='workout-index'),
  path('workouts/<int:workout_id>/', views.workout_detail, name='workout-detail'),
  path('workouts/create', views.WorkoutCreate.as_view(), name='workout-create'),
  path('workouts/<int:pk>/update/', views.WorkoutUpdate.as_view(), name='workout-update'),
  path('workouts/<int:pk>/delete/', views.WorkoutDelete.as_view(), name='workout-delete'),
  path('workouts/<int:workout_id>/add-set/', views.add_set, name='add-set'),
  path('workouts/<int:workout_id>/delete-set/<int:set_id>/', views.set_delete, name='set-delete'),
]

wellfit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

DURATION_CHOICES  = (
  ('15 Minutes', '15 Minutes'),
  ('30 Minutes', '30 Minutes'),
  ('45 Minutes', '45 Minutes'),
  ('1 Hour', '1 Hour'),
  ('1.5 Hours', '1.5 Hours'),
  ('2 Hours', '2 Hours'),
  ('More than 2 Hours', 'More than 2 Hours'),
)

WORKOUT_TYPE_CHOICES = [
    ('cardio', 'Cardio'),
    ('weightlifting', 'Weightlifting'),
    ('flexibility', 'Flexibility'),
    ('HIIT', 'High-Intensity Interval Training'),
    ('yoga', 'Yoga'),
    ('pilates', 'Pilates'),
    ('swimming', 'Swimming'),
    ('cycling', 'Cycling'),
    ('walking', 'Walking'),
    ('other', 'Other'),
]


# Create your models here.

class Workout(models.Model):
  date = models.DateField()
  duration = models.CharField(
    max_length=50,
    choices=DURATION_CHOICES,
    default=DURATION_CHOICES[0][0]
  )
  description = models.CharField(max_length=1000)
  workout_type = models.CharField(
        max_length=20,
        choices=WORKOUT_TYPE_CHOICES,
        default=WORKOUT_TYPE_CHOICES[0][0]
    )
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('workout-detail', kwargs={'workout_id': self.id})
  
  def worked_out_today(self):
    today = date.today()
    return Workout.objects.filter(user=self.user, date=today).exists()
  

class Set(models.Model):
  rep = models.IntegerField()
  movement = models.CharField(max_length=250)
  weight = models.IntegerField()
  equipment = models.CharField(max_length=100)
  workout = models.ForeignKey(Workout, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.movement} with {self.rep} reps"

main_app/forms.py
from django.forms import ModelForm, NumberInput
from .models import Set, Workout
from django import forms

class SetForm(ModelForm):
  class Meta:
    model = Set
    fields = ['movement', 'rep', 'weight', 'equipment'] 
    widgets = {
      'rep': NumberInput(attrs={'step': 1}),
      'weight': NumberInput(attrs={'step': 5}),
    }


class WorkoutForm(forms.ModelForm):
  class Meta:
    model = Workout
    fields = ['date', 'workout_type', 'duration', 'description']

  date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
  description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Workout, Set
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms
from django.urls import reverse
from .forms import SetForm, WorkoutForm
from datetime import date


# PROTECT ROUTES: 
# def (view functions): @login_required
# class(class-based views): LoginRequiredMixin

# Create your views here.
class Login(LoginView):
  template_name = 'login.html'

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

@login_required
def workout_index(request):
  workouts = Workout.objects.filter(user=request.user)
  user=request.user
  today = date.today()
  request.has_worked_out_today = Workout.objects.filter(user=user, date=today).exists()
  workouts = Workout.objects.filter(user=request.user).order_by('-date')
  return render(request, 'workouts/index.html', {'workouts': workouts})

@login_required
def workout_detail(request, workout_id):
  workout = Workout.objects.get(id=workout_id)
  set_form = SetForm()
  return render(request, 'workouts/detail.html', {'workout': workout, 'set_form': set_form })

class WorkoutCreate(LoginRequiredMixin, CreateView):
  model = Workout
  form_class = WorkoutForm

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

  def get_success_url(self):
    return reverse('workout-detail', kwargs={'workout_id': self.object.id})
  

class WorkoutUpdate(LoginRequiredMixin, UpdateView):
  model = Workout
  # fields = ['date', 'title', 'duration', 'description']
  form_class = WorkoutForm

class WorkoutDelete(LoginRequiredMixin, DeleteView):
  model = Workout
  success_url = '/workouts/'

@login_required
def add_set(request, workout_id):
  form = SetForm(request.POST)
  if form.is_valid():
    new_set = form.save(commit=False)
    new_set.workout_id = workout_id
    new_set.save()
  return redirect('workout-detail', workout_id=workout_id)

@login_required
def set_delete(request, workout_id, set_id):
  if request.method == 'POST':
    set_to_delete = Set.objects.get(id=set_id)
    set_to_delete.delete()
    return redirect('workout-detail', workout_id=workout_id)
  else:
    return redirect('workout-detail', workout_id=workout_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/about.css' %}"/>
{% endblock%}

{% block content %}

<section class="left">
  <img src="{% static "images/WellFit-logo.svg" %}" alt="WellFit Logo">
  <!-- links here -->
</section>
<section class="right">
  <hr>
  <h1>Why WellFit?</h1>
  <p>WellFit is not just another fitness app; it's a transformative experience that empowers you to take control of your health and well-being. In a world filled with distractions and hectic schedules, we understand the challenges of maintaining a consistent fitness routine. That's why WellFit is here to make your fitness journey more accessible, enjoyable, and effective than ever before.</p>
  <p>At WellFit, we believe in the power of progress. We're here to help you set and achieve your fitness goals, no matter how big or small. Whether you're looking to build strength, improve endurance, lose weight, or simply lead a healthier lifestyle, WellFit provides you with a tool to support your success.</p>
</section>

{% endblock%}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&family=DM+Sans:opsz@9..40&family=DM+Serif+Display&display=swap" rel="stylesheet">
  <title>WellFit - Workout Tracker</title>
  <link rel="icon" type="image/x-icon" href="{% static "images/WellFit-logo.svg" %}">
  <link rel="stylesheet" type='text/css' href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <nav class="container">
      <a href="{% url 'home' %}">
        <img 
          src="{% static "images/WellFit-logo.svg" %}"
          alt="WellFit Logo"
        >
      </a>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'workout-index' %}">Profile</a></li>
          <li><a href="{% url 'workout-create' %}">Log a Workout</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="/">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/home.css' %}"/>
{% endblock%}

{% block content %}

  <section class="banner">
    <div class="banner-text">
      <img src="{% static "images/WellFit-logo.svg" %}" alt="WellFit Logo">
      <h1 class="title">Get ready </br>for change </br>to happen</h1>
      {% if user.is_authenticated %}
      <a href="{% url 'workout-create' %}"><button class="bw-btn">Log a Workout</button></a>
      {% else %}
      <a href="/"><button class="bw-btn">Sign In</button></a>
      {% endif %}
    </div>
    <div class="banner-image">
      <div></div>
    </div>
  </section>
  <section class="benefits">
    <h1 class="home-scroll-img" id="no-border">Why should </br>you use </br>WellFit?</h1>
    <div class="home-scroll-img"  id="img1">
      <div class="img-txt">
        <h1>Did you know...</h1>
        <p>You're more likely to reach goals if you record them</p>
      </div>
    </div>
    <div class="home-scroll-img" id="img2">
      <div class="img-txt">
      <h1>Track Progress</h1>
      <p>Easily see how far you have come</p>
    </div>
    </div>
    <div class="home-scroll-img" id="img3">
      <div class="img-txt">
      <h1>Customize Workouts</h1>
      <p>Never forget a workout, and customize them moving forward</p>
    </div>
    </div>
    <div class="home-scroll-img" id="img4">
      <div class="img-txt">
      <h1>Stay Accountable</h1>
      <p>Holding yourself accountable keeps you moving forward</p>
    </div>
    </div>
    <div class="home-scroll-img" id="img5">
      <div class="img-txt">
      <h1>Have Fun</h1>
      <p>Remeber all the fun workouts you've done</p>
    </div>
    </div>
  </section>
  <section class="orange-banner">
    <div><p>WellFit is your fitness companion, simplifying your wellness journey. Our platform offers a place for you to monitor your progress. Whether you're building strength, boosting endurance, or leading a healthier lifestyle, WellFit has you covered. Join our community, find motivation, and transform your life, one workout at a time.</p></div>
    <div><h1>Unlock your potential, </br>One day at a time.</h1></div>
    
    
  </section>
  <section class="cta">
    <div class="cta-img">
      <div class="cta-img-div"></div>
    </div>
    <div class="cta-txt">
      <h1>Keeping track of your workouts digitally has never been better</h1>
      <p>Recording your fitness goals is a powerful tool that significantly increases your likelihood of achieving them. When you write down your objectives, you are forced to articulate and clarify your aspirations, turning abstract ideas into concrete plans. Moreover, the act of tracking your progress provides motivation, as it allows you to witness your accomplishments and encourages you to continue striving toward your goals. Additionally, recording your fitness journey helps you stay accountable, as it creates a sense of responsibility to follow through with your plans. Overall, this simple practice not only boosts your chances of success but also enhances your commitment to a healthier and more active lifestyle.</p>
    </div>
  </section>
  </section>


{% endblock%}

main_app/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/login.css' %}"/>
{% endblock%}

{% block content %}

<section class="left">
  <img src="{% static "images/WellFit-logo.svg" %}" alt="WellFit Logo">
</section>
{% if not user.is_authenticated %}
  <section class="right">
    <form action="{% url 'login' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock%}

main_app/templates/main_app/set_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<!-- stylesheet -->
{% endblock%}

{% block content %}

<h1>Confirm Delete</h1>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'workout-detail' workout.id %}"><button>Cancel</button></a>
  <button type="submit">Delete</button>
</form>

{% endblock%}

main_app/templates/main_app/workout_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/workouts/workout-confirm-delete.css' %}"/>
{% endblock%}

{% block content %}

<h1>Are you sure you want to delete <span id="wrkt">{{ workout.workout_type}}</span> ?</h1>

<form action="" method="post" class="form btn-div">
  {% csrf_token %}
    <a href="{% url 'workout-detail' workout.id %}"><button>Cancel</button></a>
    <button type="submit">Delete</button>
</form>

{% endblock%}

main_app/templates/main_app/workout_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/form.css' %}"/>
{% endblock%}

{% block content %}

{% if workout %}
  <h1>Edit {{ workout.title }}</h1>
{% else %}
  <h1>Log a New Workout</h1>
  <hr>
{% endif %}
<form  method="post" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <div class="btn-div">
    <button type="submit">Log Workout</button>
  </div>
</form>

{% endblock%}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div>
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p>{{ error_message }}</p>
{% endif %}
<form action="" method="post" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <div class="btn-div">
    <button type="submit" >Submit</button>
  </div>
</form>

{% endblock %}

main_app/templates/workouts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/workouts/workout-detail.css' %}"/>
{% endblock%}

{% block content %}

  <div class="header">
    <h1>{{workout.workout_type}}</h1>
  </div>
  </div> 
  <div class="wrkt">
    <div class="wrkt-detials">
      <div class="date">
        <h1>Date: </h1>
        <p>{{workout.date}}</p>
      </div>
      <div class="duration">
        <h1>Duration: </h1>
        <p>{{workout.duration}}</p>
      </div>
    </div>
    <div class="description">
      <p>{{workout.description}}</p>
    </div>
  </div>
  <div class="btn-div">
    <a href="{% url 'workout-update' workout.id %}"><button>Update</button></a>
    <a href="{% url 'workout-delete' workout.id %}"><button>Delete</button></a>
  </div>
  <div class="if-set">
      {% if workout.set_set.all %}
      <h1 class="">Sets</h1>
      {% else %}
      <h1 class="if-no-sets">You have no sets associated with this workout</h1>
      {% endif%}
    </div>
    <div class="set-container">
      {% for set in workout.set_set.all %}
      <div class="set-card">
        <div class="movement">
          <h1>{{ set.movement }}</h1>
        </div>
        <div class="set-on-flip">
          <div class="reps">
            <h1>No. Reps:</h1>
            <p>{{ set.rep }}</p>
          </div>
          <div class="weight">
            <h1>Weight:</h1>
            <p>{{ set.weight }}</p>
          </div>
          <div class="equip">
            <h1>Equipment Used:</h1>
            <p>{{ set.equipment }}</p>
          </div>
          <div class="delete">
            <form method="POST" action="{% url 'set-delete' workout.id set.id %}" id="delete-set-div">
              {% csrf_token %}
              <button type="submit" class="bw-btn" id="set-delete-btn">X</button>
            </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
<h1>Add a Set to your Workout</h1>
<form action="{% url 'add-set' workout.id %}" method="post" autocomplete="off">
  <table>
  {% csrf_token %}
  {{ set_form.as_table}}
</table>
<div class="btn-div">
  <button type="submit">Add a Set</button>
</div>
</form>
<div class="btn-div">
  <a href="{% url 'workout-index' %}"><button>Back to your profile</button></a>
</div>

{% endblock%}

main_app/templates/workouts/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css"href="{% static 'css/workouts/index.css' %}"/>
{% endblock%}

{% block content %}

<section class="index-header">
  <h1 id="workouts">WORK<br>OUTS</h1>
  <h1 id="username">by <br>{{user.username|title}}</h1>
  <img src="{% static "images/dots.svg" %}"" alt="three colorful dots">
</section>
<section class="profile-message">
  {% if request.has_worked_out_today %}
    <h1>Congrats on logging a workout today!</h1>
  {% else %}
    <h1>Looks like you haven't logged a workout yet today</h1>
    <a href="{% url 'workout-create' %}"><button>Log one now?</button></a>
  {% endif %}
</section>
<section class="workout-section">
  {% for workout in workouts %}
  <a href="{% url 'workout-detail' workout.id %}">
    <div class="workout-card">
        <h1>{{workout.workout_type}}</h1>
        <p>{{workout.date}}</p>
        <p>{{workout.duration}}</p>
      </div>
    </a>
  {% endfor %}
</section>

{% endblock%}